### ISSUE TITLE
New HTTP error 450....

### ISSUE THREAD

**Issue by coforfe** [soodoku/abbyyR#6]
Hello,

Thanks for making available your package to test Abbyy OCR.
I am processing a bunch of OCR images.  I was able to submit around 100 images following the example you includes in this vignnete:

```{r}
https://cloud.r-project.org/web/packages/abbyyR/vignettes/wiscads.html
```
But suddenly stops and responds with `Error: HTTP failure: 450`.

From that moment on, I cannot process any other image and even I get the same error with `deleteTask()` but not with `listTasks()`. I changed the way to connect to Internet with a mobile connection and it seemed to work again, but after submitting the 100 images, again the same problem with the same error.

I saw what you responded in this issue `https://github.com/soodoku/abbyyR/issues/1` and I updated CRAN version with the one you have here in GitHub, but the problem persists.

If you know any workaround or alternative....

**Comment by soodoku** [comment]
I think the point that it breaks after 100 images is useful. It either suggests throttling or blocking from abbyyR web service or from the computer. The fact that you did it from 2 different networks and got the same problem suggests that it is the web service. I would recommend opening an issue with them. I will investigate as well but cannot do it immediately.

**Comment by coforfe** [comment]
Thanks for your quick response.
When you say that the problem seems to be a "web service", you mean that is something I should talk with my ISP?, sorry I did not get you with this.
Thanks again,
Carlos.

**Comment by soodoku** [comment]
Carlos, sure. By 'web service', I meant abbyy itself. 

Abbyy has a cloud-based software. And we ping it when we use abbyyR. And sometimes the cloud based system has some limits on how frequently you can make requests, etc. 

So, one idea would be to try to get hold of someone at abbyy or to investigate on their customer forum if they have some rate limits. One way to limit number of requests per minute from our side would be to simply 'sleep' between requests.
```
Sys.sleep(10)
```

**Comment by coforfe** [comment]
Thanks!
OK. 
I will ask some Abbyy's representative in Spain if he can helps.
Yes, in the R script, as you indicated, there was a `Sys.sleep(1/100)`, I changed for a `Sys.sleep(2)`. 

But the issue is that now I get this `HTTP 450` error just when trying to delete the tasks that I previously submitted. Even with just trying to delete one of the tasks `deleteTask(all_tasks$id[1]` , I get the error.

Thanks again,
Carlos.

**Comment by LPelleg** [comment]
Hello,

I'm getting the same error when trying to use ocrFile() on some images.
I don't think it may be an issue of web service limits, since I'm working with less than 20 images, and the exact same code used to work until a few days ago.
I tried all the functions to process files/documents, but none if them seams to get launched on Abbyy web service.

According to the Abbyy documentation, the 450 error refers to some incorrect parameter in API request, but I tried changing my formula in all the possible ways I could think about.

Any idea of why the service is not responding? 
I'm not working with a free trial version, but I paid for some pages for my Abbyy app.

Thanks in advance.
Luca
