### ISSUE TITLE
Region option is not enabled for processImage() function

### ISSUE THREAD

**Issue by priyanf** [soodoku/abbyyR#8]
In processImage(): 

    querylist <- list(language = language, letterSet = letterSet, 
        regExp = regExp, textType = textType, oneTextLine = oneTextLine, 
        oneWordPerTextLine = oneWordPerTextLine, markingType = markingType, 
        placeholdersCount = placeholdersCount, writingStyle = writingStyle, 
        description = description, pdfPassword = pdfPassword)

This omits the "region" parameters as per https://ocrsdk.com/documentation/api-reference/process-text-field-method/

Hence OCR on a region cannot be done.

**Comment by soodoku** [comment]
thanks @priyanf! will fix.

**Comment by soodoku** [comment]
you can technically pass `region` and it will be passed to `abbyy_POST`. this is supported by the triple dots. but useful to add region so will do that.

**Comment by priyanf** [comment]
Hi Soodoku. Thanks for making the changes and for this great package. I still don't think it works properly.

I have installed version 0.5.3 and if I look at the processTextField function - I still do not see _region_ being passed in to _querylist_ -

![image](https://user-images.githubusercontent.com/20655392/40699355-65832ff8-63f1-11e8-9716-883ebc46e0a2.png)

Separately I tried using this option on an image and it doesn't work, so I think the bug may still persist. Thanks for your help.

**Comment by soodoku** [comment]
Thanks @priyanf! Will add that to processTextField. But again, just to note, what I did before: you can pass other arguments to the function that are not listed. The three dots you see at the end allow for that. So feel free to pass the correct version of region = "-1,-1,-1,-1" and you will see that it 'works' but will add that to the processtextfields. the reason i was confused is because you had listed the processImage function up top.

**Comment by soodoku** [comment]
actually, i will take my point back. because region will be overloaded so the way the function is written, you are screwed. so will fix.
